### ISSUE TITLE
iOS: Can't find variable: BEMCheckBoxDelegate

### ISSUE THREAD

**Issue by nmandyam** [bradmartin/nativescript-checkbox#11]
NativeScript JS app using nativescript-checkbox v 1.1.6, everything runs fine on Android. Same code-base on iOS, in the simulator, when my app does a "var CheckBox = require("nativescript-checkbox").CheckBox;", fails on line 255 in tns_modules/nativescript-checkbox/checkbox.js, says "Can't find variable: BEMCheckBoxDelegate". The BEMCheckBox pod is installed. The app crashes at the same point on the phone, too, so this is not a simulator issue. What could be the issue?

**Comment by nmandyam** [comment]
I don't know if this is relevant, but I noticed, when I ran "tns prepare ios", that it says "nativescript-checkbox 2.3.0 for ios is not compatible with the currently installed framework version 2.2.1". What I can do to fix that?

**Comment by bradmartin** [comment]
First, try this:
https://bradmartin.net/2016/07/20/ahhh-this-nativescript-plugin-doesnt-work/
If you still have issues let me know. That second warning you can likely
ignore, the plugin I think targeted 2.1 but should work okay unless this is
also an xcode8/ios10 issue.

**Comment by nmandyam** [comment]
Thanks for that tip, tried it but it still fails. And I don't know if it's an xcode thing - I just did a "tns run ios" after reinstalling the plugin. Still crashes with "Can't find...".

**Comment by nmandyam** [comment]
Finally didn't use the plugin. Replaced checkboxes on Android with switches on iOS.

**Comment by bradmartin** [comment]
I think this is a cocoapods issue locally. I can't reproduce, I use pod version 0.39 I think. Supposedly 1.0 has issues like this pulling pods down.

**Comment by llwt** [comment]
@bradmartin This fixed it for me. I owe you a 🍺!

**Comment by m4js7er** [comment]
I've run into the same issue. The problem is with `livesync`.
After adding plugin I had to:
```
rm -rf platforms/ios
tns emulate ios
```
After that my `livesync` works ok again.
I found this workaround [here](https://github.com/NathanWalker/nativescript-loading-indicator/issues/5)

**Comment by bradmartin** [comment]
Yea livesync doesn't add native libs. So once you run `tns plugin add` you have to do `run` or `build` to compile an executable

**Comment by bradmartin** [comment]
`emulate` works for now also but it potentially will be removed from the CLI in future because it has some issues and I think the team has said it wasn't really intended to be used and to reduce issues/confusion with the CLI having fewer commands I think is their plan for doing this operation at least.

**Comment by m4js7er** [comment]
@bradmartin thx for additional information
