### ISSUE TITLE
ngModel not working

### ISSUE THREAD

**Issue by aboalwi** [bradmartin/nativescript-checkbox#13]
I need to update the checked value in array
If i use [checked] instead it wont be updated will always be false unless i have some way to update the array element based on the nativeElement value :/

```
    public categories = [
      {catid: 1, name: 'Electronics', checked: false},
      {catid: 2, name: 'Furnitures', checked: false},
      {catid: 3, name: 'Home Appliance', checked: false},
      {catid: 4, name: 'Games', checked: false},
      {catid: 5, name: 'Accessories', checked: false}
    ]; 
```

```
    <StackLayout *ngFor="let cat of categories">
        <CheckBox [text]="cat.name" [(ngModel)]="cat.checked"></CheckBox>
        <Label [text]="cat.checked"></Label>
    </StackLayout> 
```

```
JS: EXCEPTION: Error in pages/categories/categories.html:24:36 caused by: No value accessor for form control with unspecified name attribute
JS: ORIGINAL EXCEPTION: No value accessor for form control with unspecified name attribute
```

**Comment by bradmartin** [comment]
I've not gotten into angular w/ nativescript to know enough here. I'll see if @NathanWalker or @triniwiz have a clue from the sample you provided.

**Comment by triniwiz** [comment]
@bradmartin i never used `ngModel` the app simply uses `[checked]="someVal"`

**Comment by devna13** [comment]
Same problem here.

@triniwiz  That's one way binding and binding property never changes when clicking the checkbox.

I ended up toggling the property value in the tap event handler...

**Comment by triniwiz** [comment]
@devna13 i handle changes with `(checkedChange)="doSomething($event)"`

**Comment by devna13** [comment]
@triniwiz  ARE YOU SURE!? There is no event called checkedChange.

**Comment by triniwiz** [comment]
```
<CheckBox [checked]="item.completed" text=""  (checkedChange)="itemChecked($event)"></CheckBox>

itemChecked(event){
let checked = event.value;
}
```

**Comment by baretka** [comment]
> ```
> <CheckBox [checked]="item.completed" text=""  (checkedChange)="itemChecked($event)"></CheckBox>
> 
> itemChecked(event){
> let checked = event.value;
> this.item.completed = value;
> }
> ```
> it's simple as above and this works because i am currently using this atm

Thanks
