### ISSUE TITLE
[Android] check mark/icon is transparent

### ISSUE THREAD

**Issue by aboalwi** [bradmartin/nativescript-checkbox#15]
Can we have something like checkColor as an attribute would be great..
It's transparent currently i'd like to set its color to white..

![Image of Yaktocat](https://s16.postimg.org/afmc8htrp/image.jpg)

**Comment by bradmartin** [comment]
It is possible, just not very quick to do. Some info here: http://stackoverflow.com/questions/20542693/how-to-change-check-box-tick-color-in-android

**Comment by bradmartin** [comment]
The new release might have something for you. @triniwiz I seen some of the styling Android stuff you added. Will that handle this case?

**Comment by bradmartin** [comment]
![answered](https://cloud.githubusercontent.com/assets/6006148/22359710/38dc1dba-e40f-11e6-8c88-4a40d295bfb6.PNG)

See demo code here using the `checkStyle` attribute: https://github.com/bradmartin/nativescript-checkbox/blob/master/demo/app/main-page.xml#L18
More info using this on README: https://github.com/bradmartin/nativescript-checkbox#styling-android

**Comment by triniwiz** [comment]
@bradmartin yes it will work he just needs to create the images 😄
