### ISSUE TITLE
Not working with tns-core-modules 2.5+

### ISSUE THREAD

**Issue by bferreirainfo** [bradmartin/nativescript-checkbox#16]
After update to ns-core-modules 2.5 im getting 

could not load view: CheckBox Type error: Cannot read property 'id' of undefined at resolverPromise(nativescript-angular/zone.js/dist/zone-nativescript.js:416:31

my setup:
ts
import { registerElement } from "nativescript-angular/element-registry";
registerElement("CheckBox", () => require("nativescript-checkbox").CheckBox);

html
<CheckBox class="loginField" style="font-size:16px;" text="Exibir Senha" checked="false"></CheckBox>

**Comment by bradmartin** [comment]
That seems to be specific to the angular piece of NativeScript and not an
issue with this plugin itself. You might want to raise an issue on that
repo, but since you're using 2.5 and currently 2.3 is the release and 2.4
is coming soon it's likely a non issue but something inconsistent with the
masters youre running. Hope that helps.

**Comment by hdeshev** [comment]
The problem isn't related to Angular (just zone.js masking exceptions, as usual). It seems there is a breaking change introduced with the latest non-uniform borders support feature: we [do not export](https://github.com/NativeScript/NativeScript/commit/a05f842a8456ba157392959da1e4178a3515334f#diff-f15bf647257a36b82d20d7f0f7677526L117) `borderWidthProperty` from `ui/styling/style` anymore. That causes the [property handler registration code](https://github.com/bradmartin/nativescript-checkbox/blob/master/checkbox.android.ts#L207) to fail.

@hamorphis, any ideas?

**Comment by bradmartin** [comment]
I would've never found that, thanks @hdeshev.

**Comment by hamorphis** [comment]
The borderWidth property was replaced by four new properties: borderTopWidth, borderRightWidth, borderBottomWidth and borderLeftWidth: https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/ui/styling/style.d.ts

**Comment by triniwiz** [comment]
Fixed https://github.com/bradmartin/nativescript-checkbox/pull/17
