### ISSUE TITLE
Service exited due to Segmentation fault: 11

### ISSUE THREAD

**Issue by vhontar** [bradmartin/nativescript-checkbox#18]
Hi, I use your plugin in angular2 + nativescript app. I registered element CheckBox for app, but when I tried to use 
`<CheckBox #cb1 text="test" checked="false"></CheckBox>`
I have got this error: "Nov 23 13:52:46 Mustangs-Mac-mini com.apple.CoreSimulator.SimDevice.EBE46F8E-0089-4E10-95B0-9E88F880083C.launchd_sim[456] (UIKitApplication:com.yourdomain.appname[0xd924]
[3887]): Service exited due to Segmentation fault: 11"
And when I deleted this checkbox attribute from view and rerun it. It worked fine. 
I used IOS emulator.
Version of the plugin: 1.2.1
nativescript: 2.4.0
I'd deleted platforms, node_modules and other stuffs before I ran app.
Do you know what maybe I have to do to resolve that problem?

**Comment by triniwiz** [comment]
Thanks for the info the plugin works fine on vanilla i'll see what can be done about this asap

**Comment by triniwiz** [comment]
You can upgrade to `1.2.2` 😄

**Comment by vhontar** [comment]
Thanks)
