### ISSUE TITLE
Android cannot get checkbox with id

### ISSUE THREAD

**Issue by mounirka** [bradmartin/nativescript-checkbox#19]
Hi guys, i followed the small tutorial you made, but when i do
```
let checkBox = topmost().getViewById('yourCheckBoxId');
checkBox.toggle();
```
It says that Property 'toggle' does not exist on type 'View'.
How can i solve? thank you

**Comment by bradmartin** [comment]
Likely TS issue, need to update/extend the `d.ts` to put that property on the checkbox. You could also try:

`let checkbox: CheckBox = ...` assuming you have `import { CheckBox } from nativescript-checkbox` on the file.

**Comment by mounirka** [comment]
Even doing: `let checkbox: CheckBox =` is say that type View is not assignable to type Checkbox.

**Comment by bradmartin** [comment]
Yea so the typings need to be updated for the compiler to recognize the prop

**Comment by bradmartin** [comment]
@mounirka I think I told you wrong it would be `let checkbox = (<CheckBox>topmost()....)` to do the correct type assignment. If I get time I'll update the typings to not require this but for now that should work to assign the type to the view instance.
