### ISSUE TITLE
How to disable the control?

### ISSUE THREAD

**Issue by manishmlv50** [bradmartin/nativescript-checkbox#20]
I have used the checkbox element as 

<CheckBox #CB14 text="Agree" checked="false"></CheckBox>

How to disable the control if condition is false

**Comment by bradmartin** [comment]
You should be able to use the `isEnabled` property from the NativeScript View class here: https://docs.nativescript.org/api-reference/classes/_ui_core_view_.view.html#isenabled

**Comment by bradmartin** [comment]
Added to demo: https://github.com/bradmartin/nativescript-checkbox/commit/c5ab46fb80462d1549b83689f337da2719660f4c#diff-3167d0572d77431a35f0f5792b8aaab0R30

Using the `isEnabled` property of the base `View` class for NativeScript components is all you need 😄
