### ISSUE TITLE
Can't change font-size through cssClass on css file

### ISSUE THREAD

**Issue by request-eduardo** [bradmartin/nativescript-checkbox#21]
Doing this failed...

`.checkbox_label {
	font-size: 5;	
}`

This also failed...

`<CheckBox text="Remember me" checked="false" class="checkbox_label" textWrap="true" fontSize="5"></CheckBox>`

The only way I have been able to change declaratively the font-size has been including an inline style property like this

`<CheckBox text="Remember me" checked="false" class="checkbox_label" textWrap="true" style="font-size: 5;"></CheckBox>`

Is this supposed to be the behavior? I have been able to work with color with no problems

**Comment by bradmartin** [comment]
Setting with a class will work in the next publish soon. Commit here  with details https://github.com/bradmartin/nativescript-checkbox/commit/596da0e3b46f41c04f885d177b6f4229bb250f03

**Comment by bradmartin** [comment]
1.2.4 published

**Comment by prince30** [comment]
I am using 3.0.3 ,but still having this issue , what to do ?

**Comment by fthuin** [comment]
@bradmartin Is this feature still available?
