### ISSUE TITLE
2.5.0 (Android) Label Color Not Preserved When Webpack Uglified

### ISSUE THREAD

**Issue by vbresults** [bradmartin/nativescript-checkbox#22]
In TNS 2.5.0 (Android), the label color is not preserved when uglified with webpack.  2.5 fixed CSS uglification issues but I think plugins need changes -- @bradmartin please confirm with @hdeshev

**Comment by hdeshev** [comment]
OTOH end users should exclude any component names from mangling the way we do it for builtin components:

https://github.com/NativeScript/nativescript-dev-webpack/blob/master/index.js#L135

**Comment by vbresults** [comment]
LGTM.
