### ISSUE TITLE
Add (tap) callback - INVALID

### ISSUE THREAD

**Issue by Dragomir-Ivanov** [bradmartin/nativescript-checkbox#24]
Hi there,
can you add (tap) caller for CheckBox, so we can get each individual toggle, instead of polling.

Thanks.

Sorry my mistake, had to look at the demo first. Please close it issue.

**Comment by bradmartin** [comment]
Tap events should work as we extend the nativescript View class

**Comment by Dragomir-Ivanov** [comment]
Hi Brad,
I was mistaken, didn't found in the the short summary, and read the demo too late. Sorry for the noise.

**Comment by bradmartin** [comment]
No worries :)
