### ISSUE TITLE
Event still firing twice on iOS

### ISSUE THREAD

**Issue by agisboye** [bradmartin/nativescript-checkbox#30]
dbf3782d71859735e2d4859fb1fc6a3322b70450 fixed the issue with events firing twice on iOS, but it only resolved the issue when tapping the checkbox itself. Tapping the adjacent label still makes the event fire twice.

**Comment by agisboye** [comment]
Here's the culprit:

https://github.com/bradmartin/nativescript-checkbox/blob/dbf3782d71859735e2d4859fb1fc6a3322b70450/checkbox.ios.ts#L157

The tap handler on the label is being added every time the checkbox loads. It should be added either once or at least be removed on each corresponding `unload` call. I've made a PR (#31), which takes the latter approach.

**Comment by triniwiz** [comment]
@agisboye yeah i forgot to remove that tap listener since i don't use the label 😄 👍

**Comment by agisboye** [comment]
No problem 😄 Would you mind pushing a new release with the fix?
