### ISSUE TITLE
Update: NativeScript 3.0 Breaking Changes - ui/core/proxy  missing

### ISSUE THREAD

**Issue by dgomezs** [bradmartin/nativescript-checkbox#33]
The upcoming release of nativescript has remove the ui/core/proxy module. Will the plugin be compatible with 3.0? any estimates on when that could happen?

Thank you very much in advanced.

**Comment by x00** [comment]
+1

**Comment by x00** [comment]
you you need a backward compatible solution?

**Comment by Cayan** [comment]
+1

**Comment by x00** [comment]
`ui/core/dependency-observable` and `ui/core/proxy` are depreciated need to use `/core/view` Property.

**Comment by bradmartin** [comment]
Yep and anyone willing to contribute here is the guide. https://github.com/NativeScript/NativeScript/wiki/Migrating-Plugins-to-NativeScript-3.0 I don't have the time right now to update and test. Sorry

**Comment by markhatchell** [comment]
Ill take a look at this at the same time I am updating https://github.com/bradmartin/nativescript-checkbox

**Comment by andreacappadona17** [comment]
Any news regarding compatibility with Nativescript 3.0?

**Comment by DimitarTachev** [comment]
I'm working on the NS 3.0 support here: https://github.com/DimitarTachev/nativescript-checkbox. It will be ready in a few days.

**Comment by triniwiz** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } Oh my I started this yesterday it's about 98% done just fixing an iOS problem 


Sent from Yahoo Mail for iPhone


On Thursday, May 18, 2017, 4:36 AM, Dimitar Tachev <notifications@github.com> wrote:


I'm working on the NS 3.0 support here: https://github.com/DimitarTachev/nativescript-checkbox. It will be ready in a few days.

**Comment by JorgeHawkins** [comment]
Still not working with 3.0.1

**Comment by bradmartin** [comment]
You might have some version issues. The demo project works with the latest
and I've seen a few apps on slack where ppl are using it recently.

**Comment by JorgeHawkins** [comment]
Nevermind, I had to rebuild my project.
