### ISSUE TITLE
Missing BEMCheckBoxDelegate

### ISSUE THREAD

**Issue by Dragomir-Ivanov** [bradmartin/nativescript-checkbox#37]
It seems that `BEMCheckBox.d.ts` and `platforms/ios/` has disappeared since 2.0.0 ( present in 2.0.0 ), which breaks the iOS runtime.

**Comment by kilka** [comment]
I am also facing this issue. Plugin was working fine on 3.0 and then I did a reinstall of my node_modules and now I am getting BEMCheckBoxDelegate is missing errors.

**Comment by kilka** [comment]
Just an update it looks like it's just the plugin repo that is messed up. If you clone from github or download from https://github.com/bradmartin/nativescript-checkbox/releases it seems to be working.

**Comment by triniwiz** [comment]
@kilka something probably went wrong with `2.1.x` version you can try using `2.0.0` for now

**Comment by NathanWalker** [comment]
A fix is coming for this today.

**Comment by NathanWalker** [comment]
@kilka @Dragomir-Ivanov `2.1.4` published now which should fix this - can you guys verify? If all good, you can close this - thank you for reporting!!

**Comment by Dragomir-Ivanov** [comment]
Thank you @NathanWalker ,
However I get this now:
[!] Unable to satisfy the following requirments:
- `BEMCheckBox (~> 1.4.1 )` required by `Podfile`

Is there any reason for this requirement?
In 2.0.0 Podfile has: pod 'BEMCheckBox'
In 2.1.4 Podfile has: pod 'BEMCheckBox', '~> 1.4.1'

**Comment by NathanWalker** [comment]
It will ensure you get the latest version of the pod :)
Do this in your project:
```
rm -rf hooks node_modules platforms
sudo rm -fr ~/.cocoapods/repos/master
pod repo update
npm i
```
Then all should be good.

**Comment by NathanWalker** [comment]
Btw, you will only need to do that once.
```
sudo rm -rf ~/.cocoapods/repos/master
```
clears the global CocoaPod specs, then `pod repo update` simple fetches latest specs. This is generally needed every couple months or as you run into stale specs with projects. But after doing that then you won't need to do that for the latest version of the checkbox pod ever again in this case.
