### ISSUE TITLE
Radiobutton usage

### ISSUE THREAD

**Issue by EddyVerbruggen** [bradmartin/nativescript-checkbox#42]
Hey peeps, love this plugin!

I know it's a checkbox plugin, but I'm currently abusing it as a radionbutton plugin as well (one of my apps requires both).

Would you be interested in a snippet to the README that explains how to achieve it in Angular?

The screengrab below is a still from [this tweet](https://twitter.com/eddyverbruggen/status/872548477687001088):

![simulator screen shot 7 jun 2017 22 02 09](https://user-images.githubusercontent.com/1426370/26899285-f12d6d52-4bce-11e7-8586-2681397bdc70.png)

**Comment by bradmartin** [comment]
@EddyVerbruggen you are a collaborator on this plugin. So feel free to merge and add this. Thanks for the help as always 👍

**Comment by EddyVerbruggen** [comment]
Ah, nice Brad, I will add a snippet to the readme (no plugin changes required really).
