### ISSUE TITLE
tns doctor issue

### ISSUE THREAD

**Issue by radhakrishnan0404** [bradmartin/nativescript-checkbox#49]
Macbooks-MacBook-Air:~ macbook$ tns doctor
WARNING: adb from the Android SDK is not installed or is not configured properly.
For Android-related operations, the NativeScript CLI will use a built-in version of adb.
To avoid possible issues with the native Android emulator, Genymotion or connected
Android devices, verify that you have installed the latest Android SDK and
its dependencies as described in http://developer.android.com/sdk/index.html#Requirements

TIP: To avoid setting up the necessary environment variables, you can use the Homebrew package manager to install the Android SDK and its dependencies.

Verifying CocoaPods. This may take more than a minute, please be patient.
  ◝ Installing iOS runtime.⸨░░░░░░░░░░░░░░░░░░⸩ ⠧ normalizeTree: sill install lo  ◞ Installing iOS runtime.⸨░░░░░░░░░░░░░░░░░░⸩ ⠙ normalizeTree: sill install lo  ◡ Installing iOS runtime.⸨░░░░░░░░░░░░░░░░░░⸩ ⠙ normalizeTree: sill install lo  ◟ Installing iOS runtime.⸨░░░░░░░░░░░░░░░░░░⸩ ⠙ normalizeTree: sill install lo  ◜ Installing iOS runtime.⸨░░░░░░░░░░░░░░░░░░⸩ ⠹ normalizeTree: sill install lo  ◠ Installing iOS runtime.⸨░░░░░░░░░░░░░░░░░░⸩ ⠹ normalizeTree: sill install lo  ◝ Installing iOS runtime.⸨    ░░░░░░░░░░░░░░⸩ ⠸ loadRequestedDeps: sill instal  ◞ Installing iOS runtime.⸨    ░░░░░░░░░░░░░░⸩ ⠙ loadRequestedDeps: sill instal  ◡ Installing iOS runtime.⸨    ░░░░░░░░░░░░░░⸩ ⠙ loadRequestedDeps: sill instal  ◟ Installing iOS runtime.⸨    ░░░░░░░░░░░░░░⸩ ⠙ loadRequestedDeps: sill instal  ◜ Installing iOS runtime.⸨    ░░░░░░░░░░░░░░⸩ ⠙ loadRequestedDeps: sill instal  ◠ Installing iOS runtime.⸨    ░░░░░░░░░░░░░░⸩ ⠙ loadRequestedDeps: sill instal  ◝ Installing iOS runtime.⸨    ░░░░░░░░░░░░░░⸩ ⠙ loadRequestedDeps: sill instal  ◞ Installing iOS runtime.⸨    ░░░░░░░░░░░░░░⸩ ⠙ loadRequestedDeps: sill instal  ◡ Installing iOS runtime.⸨    ░░░░░░░░░░░░░░⸩ ⠙ loadRequestedDeps: sill instal  ◟ Installing iOS runtime.⸨    ░░░░░░░░░░░░░░⸩ ⠙ loadRequestedDeps: sill instal  ◜ Installing iOS runtime.⸨    ░░░░░░░░░░░░░░⸩ ⠙ loadRequestedDeps: sill instal  ◠ Installing iOS runtime.⸨    ░░░░░░░░░░░░░░⸩ ⠙ loadRequestedDeps: sill instal  ◝ Installing iOS runtime.⸨    ░░░░░░░░░░░░░░⸩ ⠙ loadRequestedDeps: sill instal  ◞ Installing iOS runtime.⸨    ░░░░░░░░░░░░░░⸩ ⠙ loadRequestedDeps: sill instal  ◡ Installing iOS runtime.⸨    ░░░░░░░░░░░░░░⸩ ⠙ loadRequestedDeps: sill instal  ◟ Installing iOS runtime.⸨    ░░░░░░░░░░░░░░⸩ ⠙ loadRequestedDeps: sill instal  ◜ Installing iOS runtime.⸨    ░░░░░░░░░░░░░░⸩ ⠙ loadRequestedDeps: sill instal  ◠ Installing iOS runtime.⸨             ░░░░░⸩ ⠇ extract:tns-ios: sill doParall  ◝ Installing iOS runtime.⸨             ░░░░░⸩ ⠇ extract:tns-ios: sill doParall  ◞ Installing iOS runtime.⸨             ░░░░░⸩ ⠇ extract:tns-ios: sill doParall  ◡ Installing iOS runtime.⸨             ░░░░░⸩ ⠇ extract:tns-ios: sill doParall  ◟ Installing iOS runtime.⸨             ░░░░░⸩ ⠇ extract:tns-ios: sill doParall  ◜ Installing iOS runtime.⸨             ░░░░░⸩ ⠙ extract:tns-ios: sill doParall  ◠ Installing iOS runtime.⸨             ░░░░░⸩ ⠧ extract:tns-ios: sill doParall  ◝ Installing iOS runtime.⸨             ░░░░░⸩ ⠇ extract:tns-ios: sill doParall  ◞ Installing iOS runtime.⸨             ░░░░░⸩ ⠇ extract:tns-ios: sill doParall  ◡ Installing iOS runtime.⸨             ░░░░░⸩ ⠇ extract:tns-ios: sill doParall  ◟ Installing iOS runtime.⸨             ░░░░░⸩ ⠇ extract:tns-ios: sill doParall  ◜ Installing iOS runtime.⸨             ░░░░░⸩ ⠇ extract:tns-ios: sill doParall  ◠ Installing iOS runtime.⸨             ░░░░░⸩ ⠇ extract:tns-ios: sill doParall  ◝ Installing iOS runtime.⸨             ░░░░░⸩ ⠇ extract:tns-ios: sill doParall  ◞ Installing iOS runtime.⸨             ░░░░░⸩ ⠇ extract:tns-ios: sill doParall  ◡ Installing iOS runtime.⸨             ░░░░░⸩ ⠇ extract:tns-ios: sill doParall  ◟ Installing iOS runtime.⸨             ░░░░░⸩ ⠏ extract:tns-ios: sill doParall  ◜ Installing iOS runtime.⸨               ░░░⸩ ⠇ build:tns-ios: sill doSerial bnativescript-check-cocoapods@0.0.1 /private/var/folders/7g/gcgrdzcd01zdkv6dxsdm9dj40000gn/T/nativescript-check-cocoapods117521-59906-qkpw5.ay0fxswcdi
└── tns-ios@3.0.1 

npm WARN nativescript-check-cocoapods@0.0.1 No description
npm WARN nativescript-check-cocoapods@0.0.1 No repository field.
npm WARN nativescript-check-cocoapods@0.0.1 No license field.
  ◠ Installing iOS runtime.
  ◠ Verifying CocoaPods. This may take some time, please be patient..
Path must be a string. Received undefined
# doctor

┌─────────┬──────────────┐
│ Usage   │ Synopsis     │
│ General │ $ tns doctor │
└─────────┴──────────────┘

Checks your system for configuration problems which might prevent the NativeScript CLI from working properly.

**Comment by bradmartin** [comment]
You have something wrong on your machine but this repo is not the place to ask for help on this. The nativescript-cli has its own repository where you will get help from the authors/team of the CLI.

**Comment by radhakrishnan0404** [comment]
how to get help from developers team

**Comment by radhakrishnan0404** [comment]
@bradmartin are you able to communicate by Skype

**Comment by bradmartin** [comment]
Here is the repo for the CLI https://github.com/NativeScript/nativescript-cli - log an issue on that repo and the team will help. I am available for consulting if you'd like one on one assistance with your NS app. You can email me if that's what you'd like but this issue is best for the CLI team.

**Comment by radhakrishnan0404** [comment]
okay boss thank you @bradmartin
