### ISSUE TITLE
Change border color of iOS

### ISSUE THREAD

**Issue by Ericky14** [bradmartin/nativescript-checkbox#51]
Is it possible to change the border color of the checkbox for iOS?

I tried something like this and it didn't work. I'm not experience with native android/iOS, so I'm not sure how else to access the native properties.

```this.checkbox.nativeElement.ios.tintColor = new Color('#FFF').ios;```

**Comment by alexandruantonica** [comment]
Same here

**Comment by alexandruantonica** [comment]
@Ericky14 I found them :) 
It works for me and I did an awesome checkbox like that : 
```
if( platform.isIOS){
    this.checkbox.nativeElement.tintColor = "white";
    this.checkbox.nativeElement.onTintColor = "white";
    this.checkbox.nativeElement.onCheckColor = "white";
    this.checkbox.nativeElement.fillColor = "transparent";
}
```

**Comment by yassern** [comment]
would be awesome bring this option directly on css, can i work on a PR?
