### ISSUE TITLE
wrong Podfile BEMCheckBox v 1.4.1 doesn't exist anymore

### ISSUE THREAD

**Issue by henrychavez** [bradmartin/nativescript-checkbox#55]
Change
`pod 'BEMCheckBox', '~> 1.4.1'`
to
`pod 'BEMCheckBox'`

**Comment by EddyVerbruggen** [comment]
What's [this then](https://github.com/CocoaPods/Specs/blob/master/Specs/c/1/1/BEMCheckBox/1.4.1/BEMCheckBox.podspec.json)?

Perhaps you need a `pod repo update` on your machine?

**Comment by henrychavez** [comment]
you are right, my bad sorry.
