### ISSUE TITLE
`BEMCheckBox (~> 1.4.1)` required by `Podfile`

### ISSUE THREAD

**Issue by mshanak** [bradmartin/nativescript-checkbox#60]
hello 
this plugin woks fine with android, but when i run IOS, i have the following error in terminal

`BEMCheckBox (~> 1.4.1) required by Podfile`

how to resolve that ? 

regards

**Comment by Abdumama** [comment]
Same problem here.. how we can resolve this?

**Comment by EddyVerbruggen** [comment]
Just `pod repo update` usually does the trick for me.
