### ISSUE TITLE
Missing AOT support in latest release (3.0.0)

### ISSUE THREAD

**Issue by manojdcoder** [bradmartin/nativescript-checkbox#64]
Add `*.metadata.json` for angular module.

```
ERROR in Unexpected value 'TNSCheckBoxModule in path_to_app/node_modules/nativescript-checkbox/angular/index.js' imported by the module 'InputModule in path_to_app/app/input/input.module.ts'. Please add a @NgModule annotation.

ERROR in ./main.aot.ts
Module not found: Error: Can't resolve './app.module.ngfactory' in 'path_to_app/app'
 @ ./main.aot.ts 5:29-62
```

**Comment by EddyVerbruggen** [comment]
@manojdcoder It turns out publishing this plugin requires running `grunt publish` instead of `npm publish`. I've now overwritten `npm publish` in `package.json` so this will not happen again (PR will be submitted in a minute).

Version 3.0.1 is now available which fixes the issue.

**Comment by manojdcoder** [comment]
Thank you @EddyVerbruggen for the quick action.
