### ISSUE TITLE
Value-accessors moved in nativescript-angular

### ISSUE THREAD

**Issue by sittingbool** [bradmartin/nativescript-checkbox#67]
I encountered a problem that my app crashed not to finding the path"nativescript-angular/value-accessors/base-value-accessor". I found out that this changed in nativescript-angular to the forms subdirectory and should be changed into "nativescript-angular/forms/value-accessors/base-value-accessor". I don't know about the downward compatibility so far.

**Comment by jogboms** [comment]
#66 Pending a merge from @bradmartin
