### ISSUE TITLE
ListView  `itemTap` event doesn't work if list item has a CheckBox

### ISSUE THREAD

**Issue by erkanarslan** [bradmartin/nativescript-checkbox#74]
I hava a todo list page. Each task has a checkbox and tasks are in a ListView.

I noticed that itemTap doesn't work if there is a CheckBox inside list item template. When I remove the checkbox it works but i need the checkbox for todo page.

**Comment by bradmartin** [comment]
I would try the following approach:

```
  <ListView.itemTemplate>
                            <GridLayout class="list-item" rows="*" columns="auto, *">
                                <StackLayout col="0">
                                    <CheckBox:CheckBox class="list-check" ios:color="#555" text="{{ text }}" checked="{{ checked }}" fillColor="{{ color }}" tintColor="{{ color }}" propertyChanged="onPropertyChanged" />
                                </StackLayout>
                                <StackLayout col="1" tap="{{ itemTap }}" orientation="horizontal">
                                    <Label text="{{ 'Hello ' + text }}" textWrap="true" />
                                </StackLayout>
                            </GridLayout>
                        </ListView.itemTemplate>
```
Not use the `itemTap` event but handle what you want `itemTap` as a `tap` event on the portion of the layout related to the checkbox. In that example, I use `tap="{{ itemTap }}"` on the layout next to the checkbox.

**Comment by erkanarslan** [comment]
I applied that approach. It works but there is no ripple effect. For that, I used the ripple component. We can make it work like that but i think Checkbox component should provide that feature, otherwise lots of people will face similar problems.

Thanks @bradmartin
